apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "my-app.fullname" . }}-db-creds
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.database.secretArn | quote }}
        objectType: "secretsmanager"
