apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ include "my-app.fullname" . }}-db-external
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ .Values.istio.dbHost | quote }}
  ports:
  - number: 5432
    name: tcp-postgres
    protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
